"""FASTKEYS Gate fixtures: synthesize known-reference audio cases.

Each fixture is generated by construction, so the reference (key, chords,
melody) is exact ground truth. No manual repair of model output allowed.

Case A (fixture_hymn_G.wav): clean keyboard-style melody, G major.
  Tune: "Amazing Grace" (public domain, NEW BRITAIN), first phrase.
  Melody (G major): G3 C4 E4 C4 E4 D4 C4 A3 G3 ...
  Reference key: G Major. Chord pad: G, C, G, D, G (one per bar).
Case B (fixture_lead_D.wav): melody-forward lead + accompaniment, D major.
  Lead plays "When I Survey" (Hamburg) first line melody; pad plays D/A/G.
  Tests polyphonic handling with a dominant lead line.
Case C (fixture_pop_C.wav): keyboardist pop progression C-G-Am-F with melody.
  Four-chord loop with a simple stepwise melody on top.

Synthesis: harmonic tone = sum of sine partials (1, 0.5, 0.25, 0.125)
with exponential decay envelope, 22050 Hz mono, matching pipeline input.
"""
import numpy as np
import soundfile as sf

SR = 22050

NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']


def midi_to_freq(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def note_name(m):
    return f"{NOTE_NAMES[m % 12]}{(m // 12) - 1}"


def tone(midi, start, dur, gain=0.5, partials=(1.0, 0.4, 0.2, 0.1)):
    n = int(dur * SR)
    t = np.arange(n) / SR
    f = midi_to_freq(midi)
    sig = np.zeros(n)
    for k, a in enumerate(partials, start=1):
        sig += a * np.sin(2 * np.pi * f * k * t)
    # simple ADSR-ish envelope: 10ms attack, exp decay to 60%, 50ms release
    env = np.ones(n)
    atk = min(int(0.01 * SR), n)
    env[:atk] = np.linspace(0, 1, atk)
    rel = min(int(0.05 * SR), n)
    env[-rel:] *= np.linspace(1, 0, rel)
    env *= np.exp(-0.6 * t / max(dur, 0.01)) * 0.5 + 0.5
    return start, gain * env * sig


def render(events, total_dur):
    out = np.zeros(int(total_dur * SR))
    for start, sig in events:
        i = int(start * SR)
        j = min(len(out), i + len(sig))
        out[i:j] += sig[: j - i]
    out /= max(1e-9, np.abs(out).max())
    out *= 0.89
    return out


def N(name, octave):
    semis = {'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5,
             'F#': 6, 'G': 7, 'G#': 8, 'A': 9, 'A#': 10, 'B': 11}
    return semis[name] + (octave + 1) * 12


# ---------------- Case A: Amazing Grace, G major, clean melody + soft pad ----
# NEW BRITAIN 3/4, first phrase: G C E | C E D | C A G | ...
melody_a = [
    ('G', 3, 0.0, 0.6), ('C', 4, 0.6, 1.2), ('E', 4, 1.8, 1.2),
    ('C', 4, 3.0, 0.6), ('E', 4, 3.6, 1.2), ('D', 4, 4.8, 1.8),
    ('C', 4, 6.6, 0.6), ('A', 3, 7.2, 1.2), ('G', 3, 8.4, 1.8),
]
# pad: one chord per 3s bar: G, C, G, D
pad_a = [
    ([('G', 2), ('B', 2), ('D', 3)], 0.0, 3.0),
    ([('C', 3), ('E', 3), ('G', 3)], 3.0, 3.0),
    ([('G', 2), ('B', 2), ('D', 3)], 6.0, 2.4),
]
ev = []
for name, octv, st, du in melody_a:
    ev.append(tone(N(name, octv), st, du, gain=0.55))
for chord, st, du in pad_a:
    for name, octv in chord:
        ev.append(tone(N(name, octv), st, du, gain=0.12))
wav_a = render(ev, 10.2)
sf.write('fixture_hymn_G.wav', wav_a, SR)
print('wrote fixture_hymn_G.wav',
      [(note_name(N(n, o)), st) for n, o, st, _ in melody_a][:4], '...')

# ---------------- Case B: lead + accompaniment, D major ----------------------
# Hamburg "When I Survey" line 1 melody (D major): A3 A3 G3 F#3 E3 D3 ...
melody_b = [
    ('A', 3, 0.0, 0.5), ('A', 3, 0.5, 0.5), ('G', 3, 1.0, 0.5),
    ('F#', 3, 1.5, 0.5), ('E', 3, 2.0, 0.5), ('D', 3, 2.5, 1.0),
    ('E', 3, 3.5, 0.5), ('F#', 3, 4.0, 0.5), ('G', 3, 4.5, 0.5),
    ('A', 3, 5.0, 1.5),
]
pad_b = [
    ([('D', 2), ('F#', 2), ('A', 2)], 0.0, 3.5),
    ([('G', 2), ('B', 2), ('D', 3)], 3.5, 3.0),
]
ev = []
for name, octv, st, du in melody_b:
    ev.append(tone(N(name, octv), st, du, gain=0.6))
for chord, st, du in pad_b:
    for name, octv in chord:
        ev.append(tone(N(name, octv), st, du, gain=0.15))
wav_b = render(ev, 7.0)
sf.write('fixture_lead_D.wav', wav_b, SR)
print('wrote fixture_lead_D.wav')

# ---------------- Case C: pop loop C-G-Am-F + melody, C major -----------------
prog_c = [
    ([('C', 3), ('E', 3), ('G', 3)], 0.0, 2.0),
    ([('G', 2), ('B', 2), ('D', 3)], 2.0, 2.0),
    ([('A', 2), ('C', 3), ('E', 3)], 4.0, 2.0),
    ([('F', 2), ('A', 2), ('C', 3)], 6.0, 2.0),
]
melody_c = [
    ('E', 4, 0.0, 0.5), ('D', 4, 0.5, 0.5), ('C', 4, 1.0, 0.5),
    ('D', 4, 1.5, 0.5), ('B', 3, 2.0, 0.5), ('C', 4, 2.5, 0.5),
    ('D', 4, 3.0, 1.0), ('C', 4, 4.0, 0.5), ('A', 3, 4.5, 0.5),
    ('C', 4, 5.0, 1.0), ('A', 3, 6.0, 0.5), ('G', 3, 6.5, 0.5),
    ('F', 3, 7.0, 1.0),
]
ev = []
for chord, st, du in prog_c:
    for name, octv in chord:
        ev.append(tone(N(name, octv), st, du, gain=0.18))
for name, octv, st, du in melody_c:
    ev.append(tone(N(name, octv), st, du, gain=0.55))
wav_c = render(ev, 8.5)
sf.write('fixture_pop_C.wav', wav_c, SR)
print('wrote fixture_pop_C.wav')

# ---------------- Case D: deterministic timing gate fixture ---------------
# Four one-second chords with four precisely placed lead notes. This fixture
# is the ground truth for separating model timing from browser timing.
timing_chords = [
    ([('C', 2), ('E', 2), ('G', 2)], 0.0, 1.0),
    ([('F', 2), ('A', 2), ('C', 3)], 1.0, 1.0),
    ([('G', 1), ('B', 1), ('D', 2)], 2.0, 1.0),
    ([('C', 2), ('E', 2), ('G', 2)], 3.0, 1.0),
]
timing_melody = [
    ('C', 4, 0.25, 0.50), ('F', 4, 1.25, 0.50),
    ('G', 4, 2.25, 0.50), ('E', 4, 3.25, 0.50),
]
ev = []
for chord, st, du in timing_chords:
    for name, octv in chord:
        ev.append(tone(N(name, octv), st, du, gain=0.18))
for name, octv, st, du in timing_melody:
    ev.append(tone(N(name, octv), st, du, gain=0.75))
wav_timing = render(ev, 4.2)
sf.write('timing_fixture_C.wav', wav_timing, SR)
print('wrote timing_fixture_C.wav')

print('fixtures done')
