const {chromium}=require(process.env.FASTKEYS_PLAYWRIGHT_MODULE||'C:/Users/HomePC/Desktop/CLINCH-DEMO/node_modules/playwright-core');
const fs=require('node:fs'),assert=require('node:assert/strict'),M=require('./web/music.js');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.FASTKEYS_BROWSER||'C:/Users/HomePC/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe'});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.goto(process.env.FASTKEYS_SERVER_URL||'http://127.0.0.1:8011');
 const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/analyze'),{timeout:240000});await page.locator('#audioFileInput').setInputFiles('chopin_e_minor_30s.wav');const response=await responsePromise;assert.equal(response.status(),200);const data=await response.json();fs.writeFileSync('evidence/chopin-minor-analysis.json',JSON.stringify(data,null,2));await page.locator('#screenWorkspace').waitFor({state:'visible'});
 const state=()=>page.evaluate(()=>({time:document.querySelector('audio').currentTime,degree:document.querySelector('#currentDegree').textContent,chord:document.querySelector('#currentChord').textContent,solfa:document.querySelector('#currentSolfa').textContent,note:document.querySelector('#currentNote').textContent,melody:[...document.querySelectorAll('.active-melody')].map(e=>+e.dataset.midi)}));
 const proof={source:'https://commons.wikimedia.org/wiki/File:FChopinPreludeOp28n4.OGG',credit:'Porticodoro / SmartCGArt Media Productions, CC BY 3.0',excerpt:'first 30 seconds, mono 22050 Hz WAV',expectedKey:'E Minor',detectedKey:data.key,confidence:data.key_confidence,chords:await page.locator('.chord-item-name').allTextContents(),solfa:[...new Set(await page.locator('.solfa-item-syllable').allTextContents())],events:[]};
 await page.click('#btnPlayPause');await page.waitForFunction(()=>document.querySelector('audio').currentTime>2,{},{timeout:30000});proof.events.push(await state());await page.waitForFunction(()=>document.querySelector('audio').currentTime>5);proof.events.push(await state());await page.screenshot({path:'evidence/chopin-minor-playing.png',fullPage:true});await page.click('#btnPlayPause');
 for(const t of [10,20,4]){await page.locator('#timelineTrack').fill(String(t));await page.locator('#timelineTrack').dispatchEvent('input');await page.waitForTimeout(100);const s=await state(),expected=M.moment(data,t);assert.equal(s.note,expected.melody?.note||'Rest');assert.equal(s.degree,expected.chord?.degree||'·');proof.events.push(s);}
 await page.screenshot({path:'evidence/chopin-minor-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'evidence/chopin-minor-mobile.png',fullPage:true});
 assert(proof.solfa.every(x=>!x.includes('/')));proof.dMinorScale=[62,64,65,67,69,70,72].map((midi,i,a)=>M.melody(a.map((midi,j)=>({midi,start:j,end:j+1})),i,'D Minor').solfa);proof.dMinorBb=M.chord({chord:'A#'},'D Minor').name;
 fs.writeFileSync('evidence/minor-proof.json',JSON.stringify(proof,null,2));console.log(proof);assert.equal(data.key,'E Minor');assert(proof.events[1].time>proof.events[0].time);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
